# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: CIjhipster
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MTBjNzkxNjZlZGVmODQwYmM3Y2ZmNDZmZDQ5OGY0OGNiOGJkOWIzMTAyMjc4MmJjNjAxNzEwZDVmZGM0OGQ1ZGZiZjc3YmY3MjFjNTJjMzJlODQxZTdkZGNhMzJjNDE4ZWUzZjA4ZmJhZWU5MWEyNWY5NTNmYTBlNDFhMjViYTc=
