package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AnalysisResultAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnalysisResultAllPropertiesEquals(AnalysisResult expected, AnalysisResult actual) {
        assertAnalysisResultAutoGeneratedPropertiesEquals(expected, actual);
        assertAnalysisResultAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnalysisResultAllUpdatablePropertiesEquals(AnalysisResult expected, AnalysisResult actual) {
        assertAnalysisResultUpdatableFieldsEquals(expected, actual);
        assertAnalysisResultUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnalysisResultAutoGeneratedPropertiesEquals(AnalysisResult expected, AnalysisResult actual) {
        assertThat(actual)
            .as("Verify AnalysisResult auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnalysisResultUpdatableFieldsEquals(AnalysisResult expected, AnalysisResult actual) {
        assertThat(actual)
            .as("Verify AnalysisResult relevant properties")
            .satisfies(a -> assertThat(a.getSummary()).as("check summary").isEqualTo(expected.getSummary()))
            .satisfies(a -> assertThat(a.getSentiment()).as("check sentiment").isEqualTo(expected.getSentiment()))
            .satisfies(a -> assertThat(a.getTopic()).as("check topic").isEqualTo(expected.getTopic()))
            .satisfies(a -> assertThat(a.getEntities()).as("check entities").isEqualTo(expected.getEntities()))
            .satisfies(a -> assertThat(a.getRiskSource()).as("check riskSource").isEqualTo(expected.getRiskSource()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getModelName()).as("check modelName").isEqualTo(expected.getModelName()))
            .satisfies(a -> assertThat(a.getAnalyzedAt()).as("check analyzedAt").isEqualTo(expected.getAnalyzedAt()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnalysisResultUpdatableRelationshipsEquals(AnalysisResult expected, AnalysisResult actual) {
        assertThat(actual)
            .as("Verify AnalysisResult relationships")
            .satisfies(a -> assertThat(a.getNewsItem()).as("check newsItem").isEqualTo(expected.getNewsItem()));
    }
}
