package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AnalystProfileAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnalystProfileAllPropertiesEquals(AnalystProfile expected, AnalystProfile actual) {
        assertAnalystProfileAutoGeneratedPropertiesEquals(expected, actual);
        assertAnalystProfileAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnalystProfileAllUpdatablePropertiesEquals(AnalystProfile expected, AnalystProfile actual) {
        assertAnalystProfileUpdatableFieldsEquals(expected, actual);
        assertAnalystProfileUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnalystProfileAutoGeneratedPropertiesEquals(AnalystProfile expected, AnalystProfile actual) {
        assertThat(actual)
            .as("Verify AnalystProfile auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnalystProfileUpdatableFieldsEquals(AnalystProfile expected, AnalystProfile actual) {
        assertThat(actual)
            .as("Verify AnalystProfile relevant properties")
            .satisfies(a -> assertThat(a.getDisplayName()).as("check displayName").isEqualTo(expected.getDisplayName()))
            .satisfies(a -> assertThat(a.getTelegramChatId()).as("check telegramChatId").isEqualTo(expected.getTelegramChatId()))
            .satisfies(a ->
                assertThat(a.getNotificationEnabled()).as("check notificationEnabled").isEqualTo(expected.getNotificationEnabled())
            )
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnalystProfileUpdatableRelationshipsEquals(AnalystProfile expected, AnalystProfile actual) {
        assertThat(actual)
            .as("Verify AnalystProfile relationships")
            .satisfies(a -> assertThat(a.getCompetitorses()).as("check competitorses").isEqualTo(expected.getCompetitorses()));
    }
}
