package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CiAlertAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCiAlertAllPropertiesEquals(CiAlert expected, CiAlert actual) {
        assertCiAlertAutoGeneratedPropertiesEquals(expected, actual);
        assertCiAlertAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCiAlertAllUpdatablePropertiesEquals(CiAlert expected, CiAlert actual) {
        assertCiAlertUpdatableFieldsEquals(expected, actual);
        assertCiAlertUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCiAlertAutoGeneratedPropertiesEquals(CiAlert expected, CiAlert actual) {
        assertThat(actual)
            .as("Verify CiAlert auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCiAlertUpdatableFieldsEquals(CiAlert expected, CiAlert actual) {
        assertThat(actual)
            .as("Verify CiAlert relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getMessage()).as("check message").isEqualTo(expected.getMessage()))
            .satisfies(a -> assertThat(a.getSeverity()).as("check severity").isEqualTo(expected.getSeverity()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getReadAt()).as("check readAt").isEqualTo(expected.getReadAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCiAlertUpdatableRelationshipsEquals(CiAlert expected, CiAlert actual) {
        assertThat(actual)
            .as("Verify CiAlert relationships")
            .satisfies(a -> assertThat(a.getAnalysisResult()).as("check analysisResult").isEqualTo(expected.getAnalysisResult()))
            .satisfies(a -> assertThat(a.getAnalystProfile()).as("check analystProfile").isEqualTo(expected.getAnalystProfile()));
    }
}
