package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CollectionRunAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCollectionRunAllPropertiesEquals(CollectionRun expected, CollectionRun actual) {
        assertCollectionRunAutoGeneratedPropertiesEquals(expected, actual);
        assertCollectionRunAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCollectionRunAllUpdatablePropertiesEquals(CollectionRun expected, CollectionRun actual) {
        assertCollectionRunUpdatableFieldsEquals(expected, actual);
        assertCollectionRunUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCollectionRunAutoGeneratedPropertiesEquals(CollectionRun expected, CollectionRun actual) {
        assertThat(actual)
            .as("Verify CollectionRun auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCollectionRunUpdatableFieldsEquals(CollectionRun expected, CollectionRun actual) {
        assertThat(actual)
            .as("Verify CollectionRun relevant properties")
            .satisfies(a -> assertThat(a.getStartedAt()).as("check startedAt").isEqualTo(expected.getStartedAt()))
            .satisfies(a -> assertThat(a.getFinishedAt()).as("check finishedAt").isEqualTo(expected.getFinishedAt()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getFoundCount()).as("check foundCount").isEqualTo(expected.getFoundCount()))
            .satisfies(a -> assertThat(a.getProcessedCount()).as("check processedCount").isEqualTo(expected.getProcessedCount()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCollectionRunUpdatableRelationshipsEquals(CollectionRun expected, CollectionRun actual) {
        // empty method
    }
}
