package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CompetitorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompetitorAllPropertiesEquals(Competitor expected, Competitor actual) {
        assertCompetitorAutoGeneratedPropertiesEquals(expected, actual);
        assertCompetitorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompetitorAllUpdatablePropertiesEquals(Competitor expected, Competitor actual) {
        assertCompetitorUpdatableFieldsEquals(expected, actual);
        assertCompetitorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompetitorAutoGeneratedPropertiesEquals(Competitor expected, Competitor actual) {
        assertThat(actual)
            .as("Verify Competitor auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompetitorUpdatableFieldsEquals(Competitor expected, Competitor actual) {
        assertThat(actual)
            .as("Verify Competitor relevant properties")
            .satisfies(a -> assertThat(a.getCompetitorName()).as("check competitorName").isEqualTo(expected.getCompetitorName()))
            .satisfies(a -> assertThat(a.getWebsiteUrl()).as("check websiteUrl").isEqualTo(expected.getWebsiteUrl()))
            .satisfies(a -> assertThat(a.getIndustry()).as("check industry").isEqualTo(expected.getIndustry()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompetitorUpdatableRelationshipsEquals(Competitor expected, Competitor actual) {
        assertThat(actual)
            .as("Verify Competitor relationships")
            .satisfies(a -> assertThat(a.getAnalystProfileses()).as("check analystProfileses").isEqualTo(expected.getAnalystProfileses()));
    }
}
