package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DataSourceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataSourceAllPropertiesEquals(DataSource expected, DataSource actual) {
        assertDataSourceAutoGeneratedPropertiesEquals(expected, actual);
        assertDataSourceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataSourceAllUpdatablePropertiesEquals(DataSource expected, DataSource actual) {
        assertDataSourceUpdatableFieldsEquals(expected, actual);
        assertDataSourceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataSourceAutoGeneratedPropertiesEquals(DataSource expected, DataSource actual) {
        assertThat(actual)
            .as("Verify DataSource auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataSourceUpdatableFieldsEquals(DataSource expected, DataSource actual) {
        assertThat(actual)
            .as("Verify DataSource relevant properties")
            .satisfies(a -> assertThat(a.getSourceName()).as("check sourceName").isEqualTo(expected.getSourceName()))
            .satisfies(a -> assertThat(a.getUrl()).as("check url").isEqualTo(expected.getUrl()))
            .satisfies(a -> assertThat(a.getSourceType()).as("check sourceType").isEqualTo(expected.getSourceType()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getLastCheckedAt()).as("check lastCheckedAt").isEqualTo(expected.getLastCheckedAt()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataSourceUpdatableRelationshipsEquals(DataSource expected, DataSource actual) {
        assertThat(actual)
            .as("Verify DataSource relationships")
            .satisfies(a -> assertThat(a.getCompetitor()).as("check competitor").isEqualTo(expected.getCompetitor()));
    }
}
