package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class KeywordAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKeywordAllPropertiesEquals(Keyword expected, Keyword actual) {
        assertKeywordAutoGeneratedPropertiesEquals(expected, actual);
        assertKeywordAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKeywordAllUpdatablePropertiesEquals(Keyword expected, Keyword actual) {
        assertKeywordUpdatableFieldsEquals(expected, actual);
        assertKeywordUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKeywordAutoGeneratedPropertiesEquals(Keyword expected, Keyword actual) {
        assertThat(actual)
            .as("Verify Keyword auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKeywordUpdatableFieldsEquals(Keyword expected, Keyword actual) {
        assertThat(actual)
            .as("Verify Keyword relevant properties")
            .satisfies(a -> assertThat(a.getValue()).as("check value").isEqualTo(expected.getValue()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKeywordUpdatableRelationshipsEquals(Keyword expected, Keyword actual) {
        assertThat(actual)
            .as("Verify Keyword relationships")
            .satisfies(a -> assertThat(a.getCompetitor()).as("check competitor").isEqualTo(expected.getCompetitor()));
    }
}
