package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NewsItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNewsItemAllPropertiesEquals(NewsItem expected, NewsItem actual) {
        assertNewsItemAutoGeneratedPropertiesEquals(expected, actual);
        assertNewsItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNewsItemAllUpdatablePropertiesEquals(NewsItem expected, NewsItem actual) {
        assertNewsItemUpdatableFieldsEquals(expected, actual);
        assertNewsItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNewsItemAutoGeneratedPropertiesEquals(NewsItem expected, NewsItem actual) {
        assertThat(actual)
            .as("Verify NewsItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNewsItemUpdatableFieldsEquals(NewsItem expected, NewsItem actual) {
        assertThat(actual)
            .as("Verify NewsItem relevant properties")
            .satisfies(a -> assertThat(a.getExternalId()).as("check externalId").isEqualTo(expected.getExternalId()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getUrl()).as("check url").isEqualTo(expected.getUrl()))
            .satisfies(a -> assertThat(a.getOriginalText()).as("check originalText").isEqualTo(expected.getOriginalText()))
            .satisfies(a -> assertThat(a.getPublishedAt()).as("check publishedAt").isEqualTo(expected.getPublishedAt()))
            .satisfies(a -> assertThat(a.getCollectedAt()).as("check collectedAt").isEqualTo(expected.getCollectedAt()))
            .satisfies(a -> assertThat(a.getIsDuplicate()).as("check isDuplicate").isEqualTo(expected.getIsDuplicate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNewsItemUpdatableRelationshipsEquals(NewsItem expected, NewsItem actual) {
        assertThat(actual)
            .as("Verify NewsItem relationships")
            .satisfies(a -> assertThat(a.getDataSource()).as("check dataSource").isEqualTo(expected.getDataSource()))
            .satisfies(a -> assertThat(a.getCompetitor()).as("check competitor").isEqualTo(expected.getCompetitor()))
            .satisfies(a -> assertThat(a.getCollectionRun()).as("check collectionRun").isEqualTo(expected.getCollectionRun()));
    }
}
